### ISSUE TITLE
Doc: Add documentation for new integration (index, input, output)

### ISSUE THREAD

**Issue by karenzone** [logstash-plugins/logstash-integration-logstash#1]
- [x] Add `logstash-integration-logstash` to skip list
  - https://github.com/elastic/docs-tools/pull/95
- [x] Add documentation for new logstash-integration-logstash
    - [x] /docs/index.asciidoc
    - [x] /docs/input-logstash.asciidoc
    - [x] /docs/output-logstash.asciidoc
    - [x] Currently, links in the docs are commented. Uncomment doc links.
      - https://github.com/logstash-plugins/logstash-integration-logstash/pull/8
- [x] Generate a placeholder for `logstash-integration-logstash` plugin. Go to [the workflow](https://github.com/elastic/logstash-docs/actions/workflows/add_plugin_placeholder_in_vpr.yml), insert `integration` for the plugin type and `logstash` for the plugin name. After running the workflow we will see the draft PR under `logstash-docs` repo.
- [x] Add new docs to [Logstash Reference](https://www.elastic.co/guide/en/logstash/current/index.html) - this step will be taken care by workflow but need to run workflow and merge the generated PR.
- [x] Remove `logstash-integration-logstash` from skip list
  - https://github.com/elastic/docs-tools/issues/96
- [x] Release plugin
- [x] Verify that integration plugin docs have been picked up for [Versioned Plugin Reference]
  - make sure changes reflect into index docs
- [x] Bundle the plugin into core
  - https://github.com/elastic/logstash/pull/15359

IMPORTANT: We use headers and variables to manage linking between the Logstash Reference and the Versioned Plugin Reference. Docs must be created and implemented following a specific order of operation. Otherwise, docs try to link to files that have not been created yet, resulting in a chicken-and-egg situation that's tricky to mange our way out of. 

Related: #3

**Comment by karenzone** [comment]
Related: #3

**Comment by mashhurs** [comment]
My suggestion with this issue, to keep only tasks related to plugin docs and move rest to https://github.com/elastic/docs-tools/issues/99
