### ISSUE TITLE
Configuring common options field is not working in the Logstash-to-Logstash integration input plugin

### ISSUE THREAD

**Issue by guru00** [logstash-plugins/logstash-integration-logstash#20]
Hello Team,
@andsel @jsvd @yaauie @ycombinator 

Recently, I've upgraded my Logstash to the 8.11.3 version. Starting from the Logstash 8.11 version, the Logstash Integration Plugin is available. I was trying to use the Logstash input plugin to receive the data from another Logstash.

As per the elastic documentation, we can use the ** add_field** , ** id **, and **tags** in the Logstash input plugin. I was expecting those field values to be added in every event.

But, nothing is getting added to the event. Here attaching my logstash config which I used for testing, could you please someone check and help me resolve this issue?
`input {
    logstash {
      port => 9801
      host => "0.0.0.0"
      ssl_enabled => false
      id => "logstash-0"
      add_field => { 
          "from_other_logstash" => "yes"
      }
	  tags => ["logstashdata"]
    }
}
filter {
    mutate {
      add_field => {
       "data_coming_from" => "Logstash-8"
      }
    }
}
output {
    stdout {
        codec => rubydebug {
            metadata => true
        }
    }
}`

After reporting the issue in an open forum, I received confirmation that it was a bug. Therefore, I am registering the bug to get it resolved.

It would be great if this could be resolved to add the fields and tags in the "**Logstash**" input plugin like other plugins.  

Elastic open forum link: [https://discuss.elastic.co/t/logstash-integration-plugin-configuration-option-field-issue-logstash-input-plugin-add-filed-issue/351439](url)

https://discuss.elastic.co/t/logstash-integration-plugin-configuration-option-field-issue-logstash-input-plugin-add-filed-issue/351439

Thanks in advance! 
Siva

**Comment by yaauie** [comment]
(no need to tag a list of individual contributors)

I can confirm that the extra options are not handled, because neither does this plugin send `LogStash::Plugin::Inputs::Base#decorate`  on the events it receives from its inner http input plugin instance nor does it propagate the configuration down to that inner plugin so that the inner plugin can do so.

This is certainly a bug, and we will work to prioritise a fix.

**Comment by mashhurs** [comment]
v1.0.2 version of `logstash-integration-logstash` plugin is [published with this change](https://rubygems.org/gems/logstash-integration-logstash/versions/1.0.2-java)

**Comment by guru00** [comment]
Hi @mashhurs @yaauie  
Thanks for your response and actions. 

May I know when can we expect this feature to be available in the official release of Logstash?

Thanks 
Siva

**Comment by mashhurs** [comment]
> Hi @mashhurs Thanks for your response and actions.
> 
> May I know when can we expect this feature to be available in the official release of Logstash?
> 
> Thanks Siva

This will be available in upcoming any (major, minor, patch) releases. Regardless of Logstash core update, you can update with `bin/logstash-plugin update` or install specific version of the plugin with `bin/logstash install` command anytime. Please refer to [this doc](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html#updating-plugins)
